### PR TITLE
quick-fix to add english text to gene dropdowns

### PR DESCRIPTION
**Pull request by iSharingan**
I'll work on the type-changing (as mentioned in the GBATemp post) after I sleep. Should only take a moment to nail down the byte once I generate few near-identical saves (and may net some custom monstie color changes, as I think I'm seeing some RGBA values here - at least at first glance - although that could be saddle color, as I know there's at least blue and red saddles - which will be another pet project [whether RGBA or bit controlled]). Implementing a new data field entry will take a little longer as I'm not up to snuff on the actual formatting for things like that...

### CODE REVIEW

**Comment by quackerd** [comment]
The translation looks good. I'm merging it into a temporary branch for now. I'll change the code to load the new gene txt then commit to master.

Thanks for the hard work!

**Comment by iSharingan** [comment]
There shouldnt be a need to change anything. I renamed the original file so I could sub the new one with the original's name. Just build and youre done.

**Comment by iSharingan** [comment]
Once I get the item names done, it can be done the same way

**Comment by quackerd** [comment]
The editor also supports JPN version. I think it's better to use JPN translations for JPN saves.

**Comment by iSharingan** [comment]
Fair enough. A language setting option could allow manual toggling, which could appease more people in the long run (and alow for PAL translations if ever needed)

**Comment by quackerd** [comment]
That's a reasonable feature. I'll add it soon in my free time.

**Comment by iSharingan** [comment]
alright found the byte for current element. on the monster export binary, its the byte at 0xab. values are as follows:

00: no element
01: Fire
02: Water
03: Thunder
04: Ice
05: Dragon
06: Poison (not normally possible)
07: Noxious Poison (not normally possible) <-starting here color of monstie doesn't change
08: Paralysis (not normally possible)
09: Sleep (not normally possible)
0A: None (possibly hidden blast?). the few I checked past here also seemed to have no element, so not worth including as valid input.

~~as a side note, when element is changed, 0x9C seems to change form 03 to 01 (tested on 2 monsties with different default elements, one from null element to fire and one from innate fire to dragon. 3 seems to indicate an innate element and 1 is forcibly changed via genes, as element is explicitly sated in either case)~~ nvm. found other monsties with different default values. this isnt relevant

lastly, [Monstie name length is valid to 32 characters](https://cdn.discordapp.com/attachments/337732730919845889/418984193947860992/lol.jpg) (I stopped at 30 bc I didnt want to run into any actual data. At about character 19-22 it leaves the screen and just keeps going when viewed on the summary page). Perhaps an override for people trying to use the monstie's default name (default names easily break the 10 character limit often) could be added (or make the warning not revert name changes)?

**Comment by iSharingan** [comment]
not-quite-obligatory 'bump' for the email notification. 'Data mining' finalized for findings in above post.

ofc before I'm fully 'done' here I'll prolly nail down character customization bytes, ~~saddle color for monsties~~ [rest in pieces, easy saddle color editing...], and the elsewhere-mentioned item and key item lists :stuck_out_tongue:

I tend to exhaust options when [r]aiding an editor's development like this :stuck_out_tongue: (I did the same thing with APM on the MHGen editor, among others across other forums) I'm very inexperienced with coding from scratch, but I can find offsets/break values/datamine like no-one's business (including reverse-engineering code/game mechanics). Don't feel obligated to include everything I find (and let me know if it's ever unwelcome. Text sucks for translating tone of voice and body language)

**Comment by quackerd** [comment]
Great! I'll take a look at that offset when I have time. I didn't test the actual size limit of the name. I think I just used whatever users are allowed to input max? But 32 chars seem legit. I can make the change later.

**Comment by iSharingan** [comment]
no wait. 32 is ridiculously long and really shouldn't be used. 20 should be about the upper limit as 18 are used for Shrouded Nerscylla, the longest default name I can find. a warning for going over 10 wouldn't be bad for keeping nicknames 'legit' - though like in other MH titles, word blacklist (if such a thing exists in MHStories - I never try to test that in any game) bypassing is still possible via save editor as those checks are done only when typing the messages/names in-game.

anyway, on saddle colors: I give up :stuck_out_tongue:
I used a common Aptonoth (red saddle) and the amiibo Navtonoth (blue saddle) and edited both to be identical in the editor. The difference analysis turned up 16 possibilities, 10 of which I already confirmed to be active effects/moves (that update automatically after battle, so its not worth adding to the editor). This ofc left 6 possible bytes, each easy enough to test on separate copies. sadly all 6 didnt do jack (not to color of the saddle, monstie look/color, any stats, etc. - though one removed a passive effect but that was also a moot effect as it auto-updates after battle), so I'm literally out of options for where it can be (plus its not that important other than vanity saddle coloration)

**Comment by quackerd** [comment]
Maybe the saddle color is tied to the class/type of monsters in the source code. I actually don't know that much about different saddle colors ( didn't know this was a thing before you mentioned it).

**Comment by iSharingan** [comment]
I have reason to suspect it has to do with special monsters, though I swear I got a blue saddle on non-amiibo, non-DLC monsters before. I'll back-burner it, just the same, but not expecting much if any progress.

~~Edit: confirmed they're all special monsters (can't be released). not sure if there's an actual flag or not in the save file, though (it might be in the mhr_dlc or mhr_sys files).~~ nope still not it

**Comment by iSharingan** [comment]
Sent a DM on GBAtemp with new info for review at your convenience (seriously. there's no rush, but posting here in the likely case you just haven't checked GBATemp in ages).

also I'm now 99% sure the saddle color has to do with hatching conditions ~~though past failed explanations have me still slightly skeptical about this time~~ - possibly egg color variant (each species has 4 egg color pattern variants) or having several gene bingos when the game generates the egg (as its unaffected by gene editing). In either case, I have exports of eggs that hatch specifically with a blue saddle, so one could be implemented as a template egg alongside the Azuros egg even if we dont find the exact byte(s).

any more findings can be discussed when you get back to me, given that you're willing.

EDIT: I GOT IT. its certain rare genes it has when hatched. I have confirmed it doesn't change after the monstie is hatched and you channel over the genes with crap genes, so there should be a flag somewhere

**Comment by quackerd** [comment]
Kk I’ll take a look this morning. Yeah I usually don’t check GBATemp.

**Comment by iSharingan** [comment]
Posting here as its easy to add, but nutriments work on the player too. The same 10 max applies and the relative offset slightly different than that of monstie nutriment buffs (I'll nail it down later). The game automatically reverts any extra, prioritizing HP, attack, then defense, so setting all to 10 results in only a HP bonus, so no need for sanity checks in the editor.

The message on GBAtemp has all customization entry data, a couple egg offsets, and other minor research data

**Comment by iSharingan** [comment]
going to compile my findings here, as I found an extra condition on Blue saddles (and the GBATemp message is rotting away unread, not that thats a problem)

for blue saddle you need (1) at least one rare gene and (2) any combination of atleast 5 but  no more than 7 genes. 0-4, 8, and 9 genes all give a red saddle regardless of what genes they are. Locked slots dont matter so long as the 2 conditions are met. Furthermore, I confirmed its not set via flag so Channeling does, indeed, update it. You can gain the saddle when conditions are met and lose it when they aren't - namely adding a 8th and 9th gene or removing the rare gene, which is kinda disappointing, IMO, as it means you cant have a fully gene'd monstie with a blue saddle.

Character data:

```
0x00 = name (20 bytes) [for starting reference]
0x18 = Skin Color
0x1c = Hair Color 1
0x20 = Eye color
0x24 = Makeup Color
*0x28 = current clothing color 1 (possibly for save preview?)
*0x2c = current clothing color 2 (possibly for save preview?)
0x30 = Hair Color 2
0x64 = hair style
*0x65 = hair gender (display model effect only. name/color options still generated with gender byte. will be changed by in-game editor)
0x7c = chin
*0x7d = eye gender
*0x7e = mouth gender
*0x7f = makeup gender
0x80 = eyes
0x81 = mouth
0x82 = Makeup
0x8C = Gender (affects clothing style and hair selection names for in-game editor)
0x8f = voice
0x90 = voice (duplicate)
0x91 = hide/show hat toggle (0=show, 1=hide)
```

offsets with an asterisk rely on other game data and will revert to legal/consistent values on battle start, so there's no point in changing them via editor.

Character data options:

```
hair names (asterisk denotes DLC tournament reward hair):
Boy:
0 Spiky
1 Tough
7 Short Natural
3 Neat Bob
b Side bangs
2 Trendy Bob
6 Wavy
9 Undercut
4 Long and Wild
d Long with Braid
5 Braids
a Buzz Cut
c Afro
8 Bald
*e Mohawk Zuros
*11 Conga Cone
*f Shaggy Narga
*12 Barioth Pompadour
*10 Spiky Rathalos
*13 Brachy Pompadour

Girl:
0 Long Braid
4 Short Simple
9 Short and Cool
8 Chin-length Bob
d Peppy Updo
A Tribal Hair
3 Short Ponytail
5 Twin Pigtails
1 Straight Long
6 Soft Curls
e Long Princess
2 Long Ponytail
7 Simple Ponytail
c Messy Ponytail
b Scruffy Pigtails
*11 Kelbi Braid
*10 Funky Kut-Ku
*f Royal Rolls
*12 Spiky Rathian
*13 Barioth Braids


chin names:
0 regular
1 pointed
2 round

eye names:
Boy:
0 bright
1 sharp
4 almond
a Cool
6 Cat Eyes
7 Mischievous
9 Hot-blooded
c Forked Eyebrows
5 Round
10 Thin
13 Reserved
d Gentle
f Sweet
2 Droopy
3 Impressionable
12 Wise
8 No Eyebrows
e Flamboyant
b Comic Book
11 Google Eyes

Girl:
0 bright
1 sharp
4 almond
7 Cool
3 Cat Eyes
6 Mischievous
12 Youthful
c Determined
5 Round
10 Thin
d Pretty
b Sleepy
f Cross-eyed
2 Droopy
e Curious
9 Soft
13 Audacious
a Wise
8 Comic Book
11 Google Eyes

mouth names:
Boy:
0 Big
1 Small
3 Felyne Mouth
4 Buck Toothed
2 Slender Lips
5 Playful

Girl:
0 Big
1 Small
2 Felyne Mouth
4 Fanged
3 Plump Lips
5 Lipstick

makeup names:
Boy:
0 none
1 Cross-shaped Scar
2 Nose Scar
3 Red Nose
4 Freckles
5 Cat Whiskers
6 Tears Paint
7 Wings Paint
8 Little Star
9 Big Star

Girl:
0 none
1 Flushed Cheeks
2 Vivid Cheeks
3 Shy
4 Beauty Mark
5 Kitten Paint
6 Tribal Paint
7 Claw Paint
8 Little Heart
9 Big Heart

gender byte: (0 boy, 1 girl) - will auto-update all other features gender bytes upon battle start

voice names:

0 Voice 1
1 Voice 2
2 Voice 3

hide hat (0 false, 1 true)
```

egg data:
```
0x00 species ID (to establish a starting point for below)
0x01 egg is present. 0 indicates 'not present' and will prevent seeing/hatching it (though it doesn't delete the egg's data), 1 is 'present' (minimal egg movement). 2 is also 'present' and usually indicates an egg with rarer/more genes (egg bounces around more).
0x03 'new' flag (1 for new)
0x05 egg pattern. valid values are 0-3. cosmetic only.
0x10-0x31 received location data. not consistent/linear for data. takes both 0x10-0x13 and 0x20-0x23 into account for sure (0x20-0x23 usually all 0s for DLC subquest eggs). 0x24-0x31 possibly involved as well.
0x49 name lock flag. unknown specific values to lock/unlock name. setting 1 locked a DLC subquest egg (previously 0), but didn't lock a normal egg. Another normal egg had a 5 there.
```

**Pull request merged**
